import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js';
import {getAuth,setPersistence,inMemoryPersistence,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js';
import * as fs from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=v=>typeof v==='string'&&(/^https:\/\//.test(v)||/^data:image\/(png|jpeg|webp);base64,/.test(v))?v:'';
const date=v=>v?.toDate? v.toDate().toLocaleString():typeof v==='number'?new Date(v).toLocaleString():'—';
let auth,db,user,view='profiles',rows=[],last=null,hasMore=false,busy=false,epoch=0,detailVersion=0;
const tell=message=>{$('notice').textContent=message;if($('detail-notice')){$('detail-notice').textContent=message;if(message)$('detail-notice').scrollIntoView({block:'nearest'});}};
function fail(e){tell(e?.code==='permission-denied'?'Access denied by Firebase. The administrator role and Chibwenzi security rules must be activated. No changes were saved.':`Unable to complete this request (${e?.code||'connection error'}). Please retry.`);}
const owner=()=>user?.email?.toLowerCase()==='aaci.yoni@gmail.com' && user.emailVerified;
const directory=p=>({name:p.name||'',age:p.age||0,gender:p.gender||'',city:p.city||'',verified:!!p.verified,moderationStatus:p.moderationStatus||'active',complete:complete(p),createdAt:p.createdAt||null});
const profileCollection=()=>owner()?'profiles':'chibwenziDirectory';
async function syncDirectory(){
  if(!owner())return;
  for(const collection of ['profiles','reports']){
    const existingIds=new Set();let cursor=null;
    do{let q=fs.query(fs.collection(db,collection),fs.orderBy(fs.documentId()),fs.limit(100));if(cursor)q=fs.query(q,fs.startAfter(cursor));const snap=await fs.getDocsFromServer(q);
      for(let i=0;i<snap.docs.length;i+=10){const batch=fs.writeBatch(db);for(const d of snap.docs.slice(i,i+10)){const p=d.data();existingIds.add(d.id);batch.set(fs.doc(db,collection==='profiles'?'chibwenziDirectory':'chibwenziReportDirectory',d.id),collection==='profiles'?directory(p):{by:p.by,targetId:p.targetId,status:p.status,at:p.at||0});}await batch.commit();}
      cursor=snap.size===100?snap.docs.at(-1):null;
    }while(cursor);
    if(collection==='profiles'){let page=null;do{let q=fs.query(fs.collection(db,'chibwenziDirectory'),fs.orderBy(fs.documentId()),fs.limit(100));if(page)q=fs.query(q,fs.startAfter(page));const snap=await fs.getDocsFromServer(q);const stale=snap.docs.filter(d=>!existingIds.has(d.id));for(let i=0;i<stale.length;i+=10){const batch=fs.writeBatch(db);for(const d of stale.slice(i,i+10))batch.delete(d.ref);await batch.commit();}page=snap.size===100?snap.docs.at(-1):null;}while(page);}
  }
}
const complete=p=>p.complete===true||Boolean(p.name&&p.age>=18&&p.gender&&p.city&&p.bio&&p.photos?.length);
const profileStatus=p=>p.moderationStatus||'active';
async function hasRole(account){
  if(!account?.email||!account.emailVerified)return false;
  const role=await fs.getDocFromServer(fs.doc(db,'chibwenziAdmins',account.email));
  return role.exists()&&role.data().enabled===true;
}
async function guard(){if(!await hasRole(auth.currentUser))throw {code:'permission-denied'};}
function zambiaDay(){const iso=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lusaka',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());return fs.Timestamp.fromDate(new Date(iso+'T00:00:00+02:00'));}
const metrics=[['profiles','Registered profiles'],['matches','Matches'],['reports','Open reports','status','open'],['verifications','Pending verifications','status','pending'],['profiles','Verified profiles','verified',true],['profiles','Suspended accounts','moderationStatus','suspended'],['profiles','Banned accounts','moderationStatus','banned'],['chibwenziAudit','Logged actions'],['chibwenziDirectory','Complete profiles','complete',true],['chibwenziDirectory','New profiles today · Zambia','createdAt',()=>zambiaDay(),'>='],['chibwenziDirectory','New profiles · last 7 days','createdAt',()=>fs.Timestamp.fromMillis(Date.now()-7*86400000),'>='],['chibwenziActivity','Active users · last 7 days','lastActiveAt',()=>fs.Timestamp.fromMillis(Date.now()-7*86400000),'>=']];
async function stats(){const current=epoch;await Promise.all(metrics.map(async([name,label,field,value,operator='=='],i)=>{try{if(!owner()&&['matches','verifications'].includes(name)){if($('stat'+i))$('stat'+i).textContent='Owner only';return;}let q=fs.collection(db,name==='profiles'?profileCollection():name==='reports'&&!owner()?'chibwenziReportDirectory':name);if(name==='chibwenziAudit'&&!owner())q=fs.query(q,fs.where('actor','==',user.uid));if(field)q=fs.query(q,fs.where(field,operator,typeof value==='function'?value():value));const n=await fs.getCountFromServer(q);if(current===epoch&&$('stat'+i))$('stat'+i).textContent=n.data().count.toLocaleString();}catch(e){if(current===epoch&&$('stat'+i))$('stat'+i).textContent='Unavailable';}}));}
async function load(reset=true){if(busy||!user)return;busy=true;const current=epoch;try{await guard();if(reset){rows=[];last=null;$('list').textContent='Loading live records…';}let q=fs.query(fs.collection(db,view==='audit'?'chibwenziAudit':view==='profiles'?profileCollection():view==='conversations'?'matches':view==='reports'&&!owner()?'chibwenziReportDirectory':view),fs.orderBy(fs.documentId()),fs.limit(50));if(view==='audit'&&!owner())q=fs.query(q,fs.where('actor','==',user.uid));if(last)q=fs.query(q,fs.startAfter(last));const result=await fs.getDocsFromServer(q);if(current!==epoch)return;last=result.docs.at(-1)||last;rows.push(...result.docs.map(d=>({...d.data(),id:d.id})));hasMore=result.size===50;render();tell('');}catch(e){if(current===epoch){$('list').textContent='Live data could not be loaded.';fail(e);}}finally{busy=false;}}
function render(){const term=$('search')?.value.trim().toLowerCase()||'',status=$('filter')?.value||'';const filtered=rows.filter(p=>JSON.stringify(p).toLowerCase().includes(term)&&(!status||(view==='profiles'?profileStatus(p):p.status)===status));$('scope').textContent=`${rows.length} records loaded · ${filtered.length} shown. Search and filters cover loaded records; use Load more for additional records. Counts above cover the whole database. Registered profiles excludes accounts without a profile.`;$('more').hidden=!hasMore;$('list').innerHTML=filtered.length?filtered.map((p,i)=>{let title=view==='conversations'?'Conversation · '+(p.users||[]).map(id=>p.profiles?.[id]?.name||id).join(' ↔ '):view==='profiles'?`${p.name||'Unnamed'} · ${p.age||'—'}`:view==='audit'?p.action:view==='reports'?p.reason||'Report':'Selfie verification';let subtitle=view==='profiles'?`${p.city||'No city'} · ${p.gender||'—'} · ${complete(p)?'Complete profile':'Incomplete profile'}`:view==='conversations'?`${(p.users||[]).join(' ↔ ')} · ${date(p.at)}`:view==='audit'?`${p.actor} · ${date(p.at)} · ${p.reason||''}`:`${p.targetName||p.userId||p.targetId||''} · ${date(p.at)}`;let image=view==='profiles'&&owner()?photo(p.photos?.[0]):'';return `<article class="row">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:''}<div class="info"><h3>${esc(title)}</h3><p>${esc(subtitle)}</p><span class="tag">${esc(view==='profiles'?profileStatus(p):p.status||'Recorded')}</span></div><button data-record="${esc(p.id)}">Review</button></article>`;}).join(''):'<p class="empty">No records match these filters.</p>';$('list').querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>detail(rows.find(p=>p.id===b.dataset.record)));}
function controls(){ $('controls').innerHTML='<input id="search" aria-label="Search loaded records" placeholder="Search loaded names, cities, IDs or report text"><select id="filter" aria-label="Filter by status"><option value="">All statuses</option>'+ (view==='profiles'?['active','suspended','banned']:['pending','open','resolved','dismissed','approved','rejected']).map(x=>`<option>${x}</option>`).join('')+'</select>'; $('search').oninput=render;$('filter').onchange=render;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.view===view)));}
function fields(p){return '<dl>'+Object.entries(p).filter(([k])=>!['photos','selfie','photo','profiles','email','phone'].includes(k)).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v?.toDate?date(v):typeof v==='object'?JSON.stringify(v,null,2):v)}</dd>`).join('')+'</dl>';}
async function audit(action,target,reason,extra={}){const ref=fs.doc(fs.collection(db,'chibwenziAudit'));return {ref,data:{actor:user.uid,action,target,reason,at:fs.serverTimestamp(),...extra}};}
async function write(action,p,value){if(view==='verifications'&&!p.userId){tell('This legacy verification request has no linked profile. Delete it or contact the owner.');return;}const reason=$('reason')?.value.trim()||(view==='verifications'?`Verification ${value} by administrator`:null);if(!reason){tell('Enter a moderation reason before saving.');return;}if(busy)return;busy=true;const buttons=[...$('detail-body').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await guard();const log=await audit(action,p.id,reason,{value});const batch=fs.writeBatch(db);batch.set(log.ref,log.data);if(view==='profiles'){if(p.id===user.uid&&value!=='active')throw {code:'cannot-block-your-own-account'};batch.set(fs.doc(db,'chibwenziModeration',p.id),{status:value,reason,actor:user.uid,at:fs.serverTimestamp(),auditId:log.ref.id});batch.update(fs.doc(db,'profiles',p.id),{moderationStatus:value,moderationAuditId:log.ref.id});batch.update(fs.doc(db,'chibwenziDirectory',p.id),{moderationStatus:value});}else{batch.update(fs.doc(db,view,p.id),{status:value,resolvedBy:user.uid,resolvedAt:fs.serverTimestamp(),auditId:log.ref.id});if(view==='reports')batch.update(fs.doc(db,'chibwenziReportDirectory',p.id),{status:value});if(view==='verifications'&&p.userId)batch.update(fs.doc(db,'profiles',p.userId),{verified:value==='approved',verifyStatus:value,verificationAuditId:log.ref.id});if(view==='verifications'&&p.userId)batch.update(fs.doc(db,'chibwenziDirectory',p.userId),{verified:value==='approved'});}await batch.commit();$('detail').close();busy=false;await load(true);await stats();tell('Saved. This action was recorded in the immutable action log.');}catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
async function deleteProfile(p){
  const reason=($('delete-reason')?.value||$('reason')?.value||'').trim();
  if(!reason){tell('Enter a deletion reason before continuing.');return;}
  if($('delete-confirm')?.value !== 'DELETE'){tell('Type DELETE to confirm permanent profile deletion.');return;}
  if(busy)return;
  if(p.id===user?.uid){tell('You cannot delete your own profile from administration.');return;}
  busy=true;
  const buttons=[...$('detail-body').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);
  try{
    await guard();
    const log=await audit('profile-delete',p.id,reason);
    const batch=fs.writeBatch(db);
    batch.set(log.ref,log.data);
    batch.delete(fs.doc(db,'profiles',p.id));batch.set(fs.doc(db,'chibwenziProfileDeletion',p.id),{auditId:log.ref.id});
    batch.delete(fs.doc(db,'chibwenziDirectory',p.id));
    await batch.commit();
    $('detail').close();busy=false;
    await load(true);await stats();
    tell('Profile deleted. Deletion recorded in the action log. Messages, reports and the sign-in account were retained.');
  }catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}
}
function deletionControls(p){
  const button=document.createElement('button');button.textContent='Delete profile';button.className='danger';
  button.disabled=p.id===user.uid;
  button.onclick=()=>{
    button.disabled=true;
    $('detail-body').insertAdjacentHTML('beforeend',`<section class="card" aria-label="Confirm profile deletion"><h3>Delete this profile permanently?</h3><p>This removes ${esc(p.name||'this user')}'s dating profile from the database. It cannot be restored here. Messages, reports, moderation records and the sign-in account remain. To prevent a new profile, use Ban first.</p><label for="delete-reason">Deletion reason (required)</label><textarea id="delete-reason" rows="2" maxlength="1000" placeholder="For example: duplicate or inappropriate profile"></textarea><p><label for="delete-confirm">Type DELETE to confirm</label><input id="delete-confirm" autocomplete="off" spellcheck="false"></p><div class="actions"><button id="delete-final" class="danger">Permanently delete profile</button><button id="delete-cancel">Cancel</button></div></section>`);
    const section=$('delete-final').closest('section');
    $('delete-final').onclick=()=>deleteProfile(p);
    $('delete-cancel').onclick=()=>{section.remove();button.disabled=false;};
    $('delete-reason').value=$('reason')?.value||'';
    $('delete-reason').focus();
  };
  $('actions').append(button);
}
async function detail(p){if(!p)return;detailVersion++;$('detail-body').innerHTML=`<p id="detail-notice" role="status" aria-live="polite"></p><h2>${esc(view==='profiles'?p.name||'User profile':'Review record')}</h2>${view==='profiles'&&owner()?`<div class="photos">${(p.photos||[]).filter(photo).map(v=>`<img src="${esc(v)}" alt="Profile photograph">`).join('')}</div>`:''}${owner()&&view==='verifications'&&photo(p.selfie||p.photo)?`<div class="photos"><img src="${esc(p.selfie||p.photo)}" alt="Submitted verification photo"></div>`:''}${fields(p)}${view==='profiles'?`<p class="muted">Profile created: ${esc(date(p.createdAt))}. A dash means the historical date was not recorded.</p>`:''}`;if(view!=='audit'&&view!=='conversations'){$('detail-body').insertAdjacentHTML('beforeend','<label for="reason">Moderation reason</label><textarea id="reason" rows="3" style="display:block;width:100%;margin-top:8px" maxlength="1000" placeholder="Explain the decision for the action log"></textarea><div class="actions" id="actions"></div>');const actions=view==='profiles'?[['Restore access','active'],['Suspend','suspended'],['Ban','banned']]:view==='reports'?[['Resolve report','resolved'],['Dismiss report','dismissed']]:[['Approve verification','approved'],['Reject verification','rejected']];for(const [label,value]of actions){const b=document.createElement('button');b.textContent=label;if(['banned','suspended','rejected'].includes(value))b.className='danger';b.onclick=()=>write(view==='profiles'?'account-status':view==='reports'?'report-status':'verification-status',p,value);$('actions').append(b);}if(view==='profiles'){deletionControls(p);activityDetails(p);if(owner())contactDetails(p);}if(owner()&&view==='reports'&&p.targetId){const b=document.createElement('button');b.textContent='View reported profile';b.onclick=async()=>{try{const snap=await fs.getDocFromServer(fs.doc(db,'profiles',p.targetId));if(!snap.exists())throw {code:'profile-not-found'};const pp={...snap.data(),id:snap.id};$('detail-body').insertAdjacentHTML('beforeend','<h2>Reported profile</h2>'+fields(pp));b.disabled=true;}catch(e){fail(e);}};$('actions').append(b);}if(owner()&&view==='reports'&&p.matchId){const b=document.createElement('button');b.textContent='Review reported conversation';b.onclick=()=>conversation(p,b);$('actions').append(b);}else if(view==='reports')$('detail-body').insertAdjacentHTML('beforeend','<p class="muted">Conversation review is available only to the owner, for reports with an attached conversation.</p>');}if(view==='conversations'&&owner()){$('detail-body').insertAdjacentHTML('beforeend','<label for="reason">Reason for reviewing this private conversation</label><textarea id="reason" maxlength="1000" rows="3"></textarea><div class="actions"><button id="review-chat">Open conversation</button></div>');$('review-chat').onclick=()=>conversation({matchId:p.id},$('review-chat'));}if(view==='verifications'&&owner())deletionVerificationControls(p);$('detail').showModal();}
function deletionVerificationControls(p){
  const b=document.createElement('button');b.className='danger';b.textContent='Delete verification request';
  b.onclick=()=>{b.disabled=true;$('detail-body').insertAdjacentHTML('beforeend','<section class="card"><h3>Delete verification request permanently?</h3><p>This removes the request and its stored selfie from this queue. The profile verification status will not change. Enter a reason above and type DELETE.</p><label for="verification-delete-reason">Deletion reason (required)</label><textarea id="verification-delete-reason" rows="2" maxlength="1000"></textarea><p>Type DELETE to confirm</p><input id="verification-delete-confirm" aria-label="Confirm verification deletion"><div class="actions"><button id="verification-delete-final" class="danger">Permanently delete request</button><button id="verification-delete-cancel">Cancel</button></div></section>');$('verification-delete-reason').value=$('reason')?.value||'';$('verification-delete-reason').focus();const section=$('verification-delete-final').closest('section');$('verification-delete-cancel').onclick=()=>{section.remove();b.disabled=false;};$('verification-delete-final').onclick=()=>deleteVerification(p);};$('actions').append(b);
}
async function deleteVerification(p){
  const reason=($('verification-delete-reason')?.value||$('reason')?.value||'').trim();if(!reason||$('verification-delete-confirm')?.value!=='DELETE'){tell('Enter a reason and type DELETE to confirm.');return;}
  if(busy||!owner())return;busy=true;
  const buttons=[...$('detail-body').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);
  try{await guard();const log=await audit('verification-delete',p.id,reason);const batch=fs.writeBatch(db);batch.set(log.ref,log.data);batch.delete(fs.doc(db,'verifications',p.id));batch.set(fs.doc(db,'chibwenziDeletion',p.id),{auditId:log.ref.id});await batch.commit();$('detail').close();busy=false;await load(true);await stats();tell('Verification request deleted. The action was logged. The profile verification status was not changed.');}catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}
}
async function contactDetails(p){
  const version=detailVersion,current=epoch;
  try{await guard();if(!owner())return;const snap=await fs.getDocFromServer(fs.doc(db,'chibwenziContacts',p.id));if(snap.exists()&&owner()&&version===detailVersion&&current===epoch)$('detail-body').insertAdjacentHTML('beforeend','<h3>Private contact · Owner only</h3>'+`<dl><dt>Email</dt><dd>${esc(snap.data().email||'Not stored')}</dd><dt>Phone</dt><dd>${esc(snap.data().phone||'—')}</dd><dt>Updated</dt><dd>${esc(date(snap.data().updatedAt))}</dd></dl>`);}catch(e){$('detail-body').insertAdjacentHTML('beforeend','<p>Private contact is unavailable. Owner access rules must be activated.</p>');}
}
async function activityDetails(p){
  const version=detailVersion,current=epoch;
  try{const snap=await fs.getDocFromServer(fs.doc(db,'chibwenziActivity',p.id));const a=snap.exists()?snap.data():{};if(current!==epoch||version!==detailVersion)return;$('detail-body').insertAdjacentHTML('beforeend',`<h3>Activity</h3><dl><dt>First tracked visit</dt><dd>${esc(date(a.firstSeenAt))}</dd><dt>Last sign-in</dt><dd>${esc(date(a.lastLoginAt))}</dd><dt>Last site activity</dt><dd>${esc(date(a.lastActiveAt))}</dd></dl><p class="muted">Historical registration dates are unavailable when they were not recorded. Sign-ins and activity are recorded from this release onward. Restored sessions count as activity, not a new login.</p>`);}catch(e){$('detail-body').insertAdjacentHTML('beforeend','<p>Activity tracking is not available yet.</p>');}
}
async function conversation(report,button){button.disabled=true;try{await guard();if(!owner())throw {code:'permission-denied'};const reason=$('reason')?.value.trim();if(!reason){tell('Enter a reason for reviewing this private conversation.');button.disabled=false;return;}const authorization=fs.doc(db,'chibwenziCases',report.matchId);const log=await audit('conversation-review',report.matchId,reason,report.id?{reportId:report.id}:{});const batch=fs.writeBatch(db);batch.set(log.ref,log.data);batch.set(authorization,{...(report.id?{reportId:report.id}:{}),actor:user.uid,at:fs.serverTimestamp(),auditId:log.ref.id});await batch.commit();let cursor=null,total=0,loaded=[];const panel=document.createElement('section');panel.innerHTML='<h2>Private conversation · Owner only</h2><p class="muted">Loading up to 200 messages per page. Pages use document IDs; loaded messages are displayed in time order. This review is recorded in the action log.</p><div class="chat-messages"></div>';const more=document.createElement('button');more.textContent='Load more messages';panel.append(more);$('detail-body').append(panel);const currentEpoch=epoch;
    const next=async()=>{more.disabled=true;try{await guard();if(!owner())throw {code:'permission-denied'};let q=fs.query(fs.collection(db,'messages'),fs.where('matchId','==',report.matchId),fs.orderBy(fs.documentId()),fs.limit(200));if(cursor)q=fs.query(q,fs.startAfter(cursor));const snap=await fs.getDocsFromServer(q);if(currentEpoch!==epoch||!panel.isConnected)return;cursor=snap.docs.at(-1)||cursor;loaded.push(...snap.docs.map(d=>d.data()));loaded.sort((a,b)=>(a.at?.toMillis?.()||a.at||0)-(b.at?.toMillis?.()||b.at||0));panel.querySelector('.chat-messages').innerHTML=loaded.map(m=>`<div class="message"><small>${esc(m.from)} · ${esc(date(m.at))}</small>${esc(m.text)}</div>`).join('');more.hidden=snap.size<200;more.textContent=`Load more messages · ${loaded.length} loaded`;}catch(e){fail(e);}finally{more.disabled=false;}};more.onclick=next;await next();}catch(e){fail(e);button.disabled=false;}}
$('close').onclick=()=>$('detail').close();$('more').onclick=()=>load(false);$('refresh').onclick=async()=>{try{await guard();await syncDirectory();}catch(e){fail(e);return;}await load(true);await stats();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(busy)return;epoch++;view=b.dataset.view;controls();load(true);});
async function start(){try{const html=await(await fetch('index.html',{cache:'no-store'})).text();const match=html.match(/const FIREBASE_CONFIG\s*=\s*(\{[\s\S]*?\});/);if(!match)throw {code:'configuration-unavailable'};const config=Object.fromEntries([...match[1].matchAll(/^\s*(\w+):\s*"([^"\r\n]+)"/gm)].map(m=>[m[1],m[2]]));const app=initializeApp(config,'chibwenzi-administration');auth=getAuth(app);db=fs.getFirestore(app);await setPersistence(auth,inMemoryPersistence);$('signin').onclick=async()=>{try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider);}catch(e){fail(e);}};$('signout').onclick=()=>signOut(auth);onAuthStateChanged(auth,async account=>{epoch++;detailVersion++;$('detail').close();$('detail-body').textContent='';user=null;rows=[];$('workspace').hidden=true;$('gate').hidden=false;$('signout').hidden=!account;$('identity').textContent=account?`Signed in as ${account.email||account.uid}`:'';if(!account){tell('Use your own administrator account. This session does not change your dating profile login.');return;}try{if(!await hasRole(account)){tell('This account has no Chibwenzi administrator role. Ask the site owner to grant access in Firebase.');return;}user=account;$('gate').hidden=true;$('workspace').hidden=false;$('stats').innerHTML=metrics.map(([,label],i)=>`<div><b id="stat${i}">…</b><span>${label==='Logged actions'&&!owner()?'My logged actions':label}</span></div>`).join('');document.querySelector('[data-view=verifications]').hidden=!owner();document.querySelector('[data-view=conversations]').hidden=!owner();controls();await syncDirectory();await load(true);await stats();}catch(e){fail(e);}});}catch(e){$('signin').disabled=true;fail(e);}}
start();
