import {initializeApp} from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js';
import {getAuth,setPersistence,inMemoryPersistence,GoogleAuthProvider,signInWithPopup,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js';
import * as fs from 'https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=v=>typeof v==='string'&&(/^https:\/\//.test(v)||/^data:image\/(png|jpeg|webp);base64,/.test(v))?v:'';
const date=v=>v?.toDate? v.toDate().toLocaleString():typeof v==='number'?new Date(v).toLocaleString():'—';
let auth,db,user,view='profiles',rows=[],last=null,hasMore=false,busy=false,epoch=0;
const tell=message=>{$('notice').textContent=message;};
function fail(e){tell(e?.code==='permission-denied'?'Access denied by Firebase. The administrator role and Chibwenzi security rules must be activated. No changes were saved.':`Unable to complete this request (${e?.code||'connection error'}). Please retry.`);}
const complete=p=>Boolean(p.name&&p.age>=18&&p.gender&&p.city&&p.bio&&p.photos?.length);
const profileStatus=p=>p.moderationStatus||'active';
async function guard(){if(!auth.currentUser||(await auth.currentUser.getIdTokenResult(true)).claims.chibwenziAdmin!==true)throw {code:'permission-denied'};}
async function stats(){const defs=[['profiles','Registered profiles'],['matches','Matches'],['reports','Open reports']];await Promise.all(defs.map(async([name,label],i)=>{try{let q=fs.collection(db,name);if(name==='reports')q=fs.query(q,fs.where('status','==','open'));const n=await fs.getCountFromServer(q);$('stat'+i).textContent=n.data().count.toLocaleString();}catch(e){$('stat'+i).textContent='Unavailable';}}));}
async function load(reset=true){if(busy||!user)return;busy=true;const current=epoch;try{await guard();if(reset){rows=[];last=null;$('list').textContent='Loading live records…';}let q=fs.query(fs.collection(db,view),fs.orderBy(fs.documentId()),fs.limit(50));if(last)q=fs.query(q,fs.startAfter(last));const result=await fs.getDocsFromServer(q);if(current!==epoch)return;last=result.docs.at(-1)||last;rows.push(...result.docs.map(d=>({...d.data(),id:d.id})));hasMore=result.size===50;render();tell('');}catch(e){if(current===epoch){$('list').textContent='Live data could not be loaded.';fail(e);}}finally{busy=false;}}
function render(){const term=$('search')?.value.trim().toLowerCase()||'',status=$('filter')?.value||'';const filtered=rows.filter(p=>JSON.stringify(p).toLowerCase().includes(term)&&(!status||(view==='profiles'?profileStatus(p):p.status)===status));$('scope').textContent=`${rows.length} records loaded · ${filtered.length} shown. Search and filters cover loaded records; use Load more for additional records. Counts above cover the whole database. Registered profiles excludes accounts without a profile.`;$('more').hidden=!hasMore;$('list').innerHTML=filtered.length?filtered.map((p,i)=>{let title=view==='profiles'?`${p.name||'Unnamed'} · ${p.age||'—'}`:view==='audit'?p.action:view==='reports'?p.reason||'Report':'Selfie verification';let subtitle=view==='profiles'?`${p.city||'No city'} · ${p.gender||'—'} · ${complete(p)?'Complete profile':'Incomplete profile'}`:view==='audit'?`${p.actor} · ${date(p.at)} · ${p.reason||''}`:`${p.targetName||p.userId||p.targetId||''} · ${date(p.at)}`;let image=view==='profiles'?photo(p.photos?.[0]):'';return `<article class="row">${image?`<img src="${esc(image)}" alt="" loading="lazy">`:''}<div class="info"><h3>${esc(title)}</h3><p>${esc(subtitle)}</p><span class="tag">${esc(view==='profiles'?profileStatus(p):p.status||'Recorded')}</span></div><button data-record="${esc(p.id)}">Review</button></article>`;}).join(''):'<p class="empty">No records match these filters.</p>';$('list').querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>detail(rows.find(p=>p.id===b.dataset.record)));}
function controls(){ $('controls').innerHTML='<input id="search" aria-label="Search loaded records" placeholder="Search loaded names, cities, IDs or report text"><select id="filter" aria-label="Filter by status"><option value="">All statuses</option>'+ (view==='profiles'?['active','suspended','banned']:['pending','open','resolved','dismissed','approved','rejected']).map(x=>`<option>${x}</option>`).join('')+'</select>'; $('search').oninput=render;$('filter').onchange=render;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.view===view)));}
function fields(p){return '<dl>'+Object.entries(p).filter(([k])=>!['photos','selfie','photo','email','phone'].includes(k)).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v?.toDate?date(v):typeof v==='object'?JSON.stringify(v,null,2):v)}</dd>`).join('')+'</dl>';}
async function audit(action,target,reason,extra={}){const ref=fs.doc(fs.collection(db,'chibwenziAudit'));return {ref,data:{actor:user.uid,action,target,reason,at:fs.serverTimestamp(),...extra}};}
async function write(action,p,value){const reason=$('reason')?.value.trim();if(!reason){tell('Enter a moderation reason before saving.');return;}if(busy)return;busy=true;const buttons=[...$('detail-body').querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{await guard();const log=await audit(action,p.id,reason,{value});const batch=fs.writeBatch(db);batch.set(log.ref,log.data);if(view==='profiles'){if(p.id===user.uid&&value!=='active')throw {code:'cannot-block-your-own-account'};batch.set(fs.doc(db,'chibwenziModeration',p.id),{status:value,reason,actor:user.uid,at:fs.serverTimestamp(),auditId:log.ref.id});batch.update(fs.doc(db,'profiles',p.id),{moderationStatus:value,moderationAuditId:log.ref.id});}else{batch.update(fs.doc(db,view,p.id),{status:value,resolvedBy:user.uid,resolvedAt:fs.serverTimestamp(),auditId:log.ref.id});if(view==='verifications'&&p.userId)batch.update(fs.doc(db,'profiles',p.userId),{verified:value==='approved',verificationAuditId:log.ref.id});}await batch.commit();$('detail').close();busy=false;await load(true);await stats();tell('Saved. This action was recorded in the immutable action log.');}catch(e){fail(e);}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
async function detail(p){if(!p)return;$('detail-body').innerHTML=`<h2>${esc(view==='profiles'?p.name||'User profile':'Review record')}</h2>${view==='profiles'?`<div class="photos">${(p.photos||[]).filter(photo).map(v=>`<img src="${esc(v)}" alt="Profile photograph">`).join('')}</div>`:''}${view==='verifications'&&photo(p.selfie||p.photo)?`<div class="photos"><img src="${esc(p.selfie||p.photo)}" alt="Submitted verification photo"></div>`:''}${fields(p)}`;if(view!=='audit'){$('detail-body').insertAdjacentHTML('beforeend','<label for="reason">Moderation reason</label><textarea id="reason" rows="3" style="display:block;width:100%;margin-top:8px" maxlength="1000" placeholder="Explain the decision for the action log"></textarea><div class="actions" id="actions"></div>');const actions=view==='profiles'?[['Restore access','active'],['Suspend','suspended'],['Ban','banned']]:view==='reports'?[['Resolve report','resolved'],['Dismiss report','dismissed']]:[['Approve verification','approved'],['Reject verification','rejected']];for(const [label,value]of actions){const b=document.createElement('button');b.textContent=label;if(['banned','suspended','rejected'].includes(value))b.className='danger';b.onclick=()=>write(view==='profiles'?'account-status':view==='reports'?'report-status':'verification-status',p,value);$('actions').append(b);}if(view==='reports'&&p.targetId){const b=document.createElement('button');b.textContent='View reported profile';b.onclick=async()=>{try{const snap=await fs.getDocFromServer(fs.doc(db,'profiles',p.targetId));if(!snap.exists())throw {code:'profile-not-found'};const pp={...snap.data(),id:snap.id};$('detail-body').insertAdjacentHTML('beforeend','<h2>Reported profile</h2>'+fields(pp));b.disabled=true;}catch(e){fail(e);}};$('actions').append(b);}if(view==='reports'&&p.matchId){const b=document.createElement('button');b.textContent='Review reported conversation';b.onclick=()=>conversation(p,b);$('actions').append(b);}else if(view==='reports')$('detail-body').insertAdjacentHTML('beforeend','<p class="muted">This report has no conversation attached. Private messages are not available for this case.</p>');}$('detail').showModal();}
async function conversation(report,button){button.disabled=true;try{await guard();const authorization=fs.doc(db,'chibwenziCases',report.matchId);const log=await audit('conversation-review',report.matchId,'Review conversation attached to report',{reportId:report.id});const batch=fs.writeBatch(db);batch.set(log.ref,log.data);batch.set(authorization,{reportId:report.id,actor:user.uid,at:fs.serverTimestamp(),auditId:log.ref.id});await batch.commit();const snap=await fs.getDocsFromServer(fs.query(fs.collection(db,'messages'),fs.where('matchId','==',report.matchId),fs.limit(200)));const messages=snap.docs.map(d=>d.data()).sort((a,b)=>(a.at||0)-(b.at||0));$('detail-body').insertAdjacentHTML('beforeend',`<h2>Reported conversation</h2><p class="muted">${messages.length} messages loaded (maximum 200; ordered by document ID when truncated). Access recorded in the action log.</p>`+messages.map(m=>`<div class="message"><small>${esc(m.from)} · ${esc(date(m.at))}</small>${esc(m.text)}</div>`).join(''));}catch(e){fail(e);button.disabled=false;}}
$('close').onclick=()=>$('detail').close();$('more').onclick=()=>load(false);$('refresh').onclick=async()=>{await load(true);await stats();};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(busy)return;epoch++;view=b.dataset.view;controls();load(true);});
async function start(){try{const html=await(await fetch('index.html',{cache:'no-store'})).text();const match=html.match(/const FIREBASE_CONFIG\s*=\s*(\{[\s\S]*?\});/);if(!match)throw {code:'configuration-unavailable'};const config=Object.fromEntries([...match[1].matchAll(/^\s*(\w+):\s*"([^"\r\n]+)"/gm)].map(m=>[m[1],m[2]]));const app=initializeApp(config,'chibwenzi-administration');auth=getAuth(app);db=fs.getFirestore(app);await setPersistence(auth,inMemoryPersistence);$('signin').onclick=async()=>{try{const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});await signInWithPopup(auth,provider);}catch(e){fail(e);}};$('signout').onclick=()=>signOut(auth);onAuthStateChanged(auth,async account=>{epoch++;user=null;rows=[];$('workspace').hidden=true;$('gate').hidden=false;$('signout').hidden=!account;$('identity').textContent=account?`Signed in as ${account.email||account.uid}`:'';if(!account){tell('Use your own administrator account. This session does not change your dating profile login.');return;}try{if((await account.getIdTokenResult(true)).claims.chibwenziAdmin!==true){tell('This account has no Chibwenzi administrator role. Ask the site owner to grant access in Firebase.');return;}user=account;$('gate').hidden=true;$('workspace').hidden=false;$('stats').innerHTML=['Registered profiles','Matches','Open reports'].map((label,i)=>`<div><b id="stat${i}">…</b><span>${label}</span></div>`).join('');controls();await load(true);await stats();}catch(e){fail(e);}});}catch(e){$('signin').disabled=true;fail(e);}}
start();
